### ISSUE TITLE
Project Direction Questions

### ISSUE THREAD

**Issue by benyanke** [spatie/uptime-monitor-app#8]
Hello,

This tool looks to be exactly what I need.

Would you be open to PRs if I were to add other features, such as these?

 * Alternate notification channels
   * such as SMS APIs like Twilio
 * Other metrics to watch
   * Load time - get alerts if the site loads too slowly
   * DNS change - get alerts if the ip changes (useful information point when a service is running on a dynamic IP)
   * Minimum/maximum return body size - ensure you're not returning a 200, but with little-to-no actual content
   * grep for content on the body - for example "Error Establishing a Database Connection" is an error which appears on Wordpress sites if the database is not available - error state could be either presence or absence of a given string in the page body
   * "deadman's ping" - send an alert if an API call is *not* made to this monitoring app in a given amount of time

These are just a few ideas which could be great expansions on your project, which I might be able to help add.

**Comment by freekmurze** [comment]
> such as SMS APIs like Twilio

If you need other notification channels, you can install [the underlying package](https://github.com/spatie/laravel-uptime-monitor) into a Laravel app of your own. The packages just uses Laravel's standard notification features, so it should be fairly straightforward to add a driver for your favourite notification provider in your Laravel app.


> Other metrics to watch

I'm open for PRs to l [the underlying package](https://github.com/spatie/laravel-uptime-monitor)  that add functionality as long as the implementation is easy to follow, non-breaking and fully tested. If you want to go ahead, best to PR one single new metric at a time.

I'm closing this issue here, send PRs to this repo: https://github.com/spatie/laravel-uptime-monitor

**Comment by benyanke** [comment]
Excellent - thank you.
